/* Quantum City — research corpus.
   Papers below are REAL arXiv entries (id + title verbatim), the newest
   six per topic from the arXiv API as of 2026-09-23. Titles containing
   TeX were passed over, since the shelf shows titles as plain text.
   Abstracts and author lists are not mirrored here; each entry links to
   its live arXiv record. "Foundational" entries link to
   a live arXiv search rather than asserting an identifier.        */

window.QC_SEEDED_ON = "2026-09-23";

/* ---- topic taxonomy -------------------------------------------------- */
window.QC_TOPICS = [
  { id:"pheno",   name:"Particle Phenomenology", arch:"hep-ph",     hue:"#4FD0E8", blurb:"Where the Lagrangian meets the detector: predictions, fits, exclusion curves.", kw:["phenomenology","collider","cross section","signature","constraint"] },
  { id:"qft",     name:"Quantum Field Theory",   arch:"hep-th",     hue:"#8FB8FF", blurb:"Amplitudes, renormalisation, the machinery under everything else.", kw:["amplitude","field theory","renormalisation","renormalization","loop","bootstrap"] },
  { id:"bsm",     name:"Beyond the Standard Model", arch:"hep-ph",  hue:"#C86FE8", blurb:"Everything the Standard Model does not explain, and the models that try.", kw:["beyond the standard model","new physics","bsm","portal","heavy neutral","z'","z prime"] },
  { id:"dm",      name:"Dark Matter",            arch:"hep-ph",     hue:"#7C6FE8", blurb:"Five sixths of the matter budget, still only gravitationally confirmed.", kw:["dark matter","freeze-in","freeze-out","relic","direct detection","wimp"] },
  { id:"axion",   name:"Axions & ALPs",          arch:"hep-ph",     hue:"#FFC45A", blurb:"The strong-CP fix that became a dark-matter candidate and a whole instrument class.", kw:["axion","alp","axion-like","peccei","haloscope","coupling to photons"] },
  { id:"dp",      name:"Dark Photons",           arch:"hep-ph",     hue:"#5AE8C0", blurb:"A kinetically mixed U(1)': the simplest portal anyone can write down.", kw:["dark photon","kinetic mixing","hidden photon","dark z","vector portal"] },
  { id:"pbh",     name:"Primordial Black Holes", arch:"astro-ph.CO",hue:"#FF7A6B", blurb:"Black holes from the primordial power spectrum — dark matter, seeds, or nothing at all.", kw:["primordial black hole","pbh","hawking","evaporation","abundance","memory burden"] },
  { id:"gw",      name:"Gravitational Waves",    arch:"gr-qc",      hue:"#6BE87A", blurb:"Strain data as a cosmological probe, from nanohertz to kilohertz.", kw:["gravitational wave","stochastic background","pulsar timing","pta","strain","binary"] },
  { id:"nu",      name:"Neutrino Physics",       arch:"hep-ph",     hue:"#4FE8D2", blurb:"Mass, mixing, and the sterile states that may or may not be there.", kw:["neutrino","seesaw","sterile","oscillation","majorana","mass ordering"] },
  { id:"coll",    name:"Collider Physics",       arch:"hep-ph",     hue:"#FF9E4A", blurb:"LHC, the muon collider, FCC — machines as hypothesis tests.", kw:["collider","lhc","muon collider","fcc","luminosity","search","detector"] },
  { id:"higgs",   name:"Higgs Physics",          arch:"hep-ph",     hue:"#FFD06B", blurb:"One scalar, an unmeasured potential, and a great deal riding on its shape.", kw:["higgs","self-coupling","trilinear","scalar potential","electroweak symmetry breaking"] },
  { id:"susy",    name:"Supersymmetry",          arch:"hep-ph",     hue:"#E86FA8", blurb:"Still the most studied extension; naturalness arguments under real pressure.", kw:["supersymmetry","susy","mssm","naturalness","superpartner","neutralino"] },
  { id:"string",  name:"String Theory",          arch:"hep-th",     hue:"#A88FFF", blurb:"Compactification, the landscape, and the swampland that bounds it.", kw:["string","swampland","compactification","landscape","moduli","holography"] },
  { id:"xdim",    name:"Extra Dimensions",       arch:"hep-ph",     hue:"#8FE8FF", blurb:"Warped and flat geometries, KK towers, and what a collider would see.", kw:["extra dimension","kaluza","warped","graviton","randall","brane"] },
  { id:"inf",     name:"Inflation",              arch:"astro-ph.CO",hue:"#FFA8D2", blurb:"The primordial power spectrum and the reheating that had to follow it.", kw:["inflation","reheating","power spectrum","slow roll","attractor","e-fold"] },
  { id:"early",   name:"Early Universe",         arch:"astro-ph.CO",hue:"#FF8F5A", blurb:"Phase transitions, bubble walls, and the first microsecond.", kw:["early universe","phase transition","bubble","nucleosynthesis","bbn","thermal history"] },
  { id:"baryo",   name:"Baryogenesis & Leptogenesis", arch:"hep-ph", hue:"#E8C06F", blurb:"Why there is anything here at all rather than a bath of photons.", kw:["baryogenesis","leptogenesis","asymmetry","sakharov","cp violation","washout"] },
  { id:"astro",   name:"Astroparticle Physics",  arch:"astro-ph.HE",hue:"#6BC0E8", blurb:"The sky as a beam line, at energies no accelerator reaches.", kw:["astroparticle","multimessenger","icecube","km3net","high energy neutrino","source"] },
  { id:"cr",      name:"Cosmic Rays",            arch:"astro-ph.HE",hue:"#E8A06B", blurb:"Ultra-high-energy particles and the century-old question of where they come from.", kw:["cosmic ray","uhecr","ultra-high energy","auger","air shower"] },
  { id:"gamma",   name:"Gamma-Ray Astronomy",    arch:"astro-ph.HE",hue:"#C0E86B", blurb:"TeV and PeV photons, and what they rule out along the way.", kw:["gamma-ray","gamma ray","tev","lhaaso","cherenkov telescope","agn"] },
  { id:"bh",      name:"Black Hole Physics",     arch:"gr-qc",      hue:"#9AA8C8", blurb:"Ringdown spectroscopy, quasinormal modes, superradiance.", kw:["black hole","ringdown","quasinormal","superradiance","horizon","kerr"] },
  { id:"modgrav", name:"Modified Gravity",       arch:"gr-qc",      hue:"#6BE8C8", blurb:"f(R), scalar-tensor, and the observations that keep narrowing them.", kw:["modified gravity","f(r)","dark energy","scalar-tensor","screening","growth"] },
  { id:"qg",      name:"Quantum Gravity",        arch:"hep-th",     hue:"#B8A8FF", blurb:"Holography, information, and the parts of the problem that are actually sharp.", kw:["quantum gravity","holography","information","entanglement","entropy","ads/cft"] },
  { id:"eft",     name:"Effective Field Theory", arch:"hep-ph",     hue:"#9FE8B8", blurb:"SMEFT and friends: parameterising ignorance responsibly.", kw:["effective field theory","smeft","eft","operator","power counting","wilson coefficient"] },
  { id:"flav",    name:"Flavour Physics",        arch:"hep-ph",     hue:"#FF8FA8", blurb:"B anomalies, lepton universality, and the most sensitive indirect probes we have.", kw:["flavor","flavour","b meson","lepton universality","rare decay","ckm"] },
  { id:"cmb",     name:"CMB Physics",            arch:"astro-ph.CO",hue:"#8FD0FF", blurb:"The oldest photons, still the tightest constraint on nearly everything.", kw:["cmb","microwave background","lensing","polarisation","polarization","acoustic"] },
  { id:"lss",     name:"Large-Scale Structure",  arch:"astro-ph.CO",hue:"#C8B8FF", blurb:"The cosmic web as a late-time record of the initial conditions.", kw:["large-scale structure","large scale structure","clustering","correlation function","survey","growth"] }
];

/* ---- live index: real arXiv records ---------------------------------- */
/* t = topic id, i = arXiv id, n = title (verbatim)                       */
window.QC_PAPERS = [
  // Particle Phenomenology
  {t:"pheno", i:"2609.24914", n:"Luminosity Signatures of Dark Sector Particles from Black Hole Evaporation in Neutron Stars"},
  {t:"pheno", i:"2609.23452", n:"Heavy-Quark Production in DIS: Mellin Moments for Phenomenology"},
  {t:"pheno", i:"2609.18607", n:"Theoretical and phenomenological aspects of the Electroweak physics WG studies for the 2026 ESPPU Physics Briefing Book"},
  {t:"pheno", i:"2609.17259", n:"High-energy QCD phenomenology with next-to-leading order BFKL eigenfunctions"},
  {t:"pheno", i:"2609.16104", n:"Rethinking search signatures: Hadronic decays of GeV-scale feebly coupled particles"},
  {t:"pheno", i:"2609.15583", n:"Generalized Parton Distributions: Phenomenology, Extraction, and Hadron Imaging"},
  // Quantum Field Theory
  {t:"qft", i:"2609.24817", n:"The Generalized Uncertainty Principle. Massless QED Renormalization"},
  {t:"qft", i:"2609.23192", n:"Renormalized Dynamical Friction in Black-Hole Spacetimes"},
  {t:"qft", i:"2609.22899", n:"Exact Amplitude Reconstruction in the Real Common-Phase Sector of Small-x Diffractive Energy Flow"},
  {t:"qft", i:"2609.20927", n:"Bootstrapping Classical Systems with Quenched Disorder"},
  {t:"qft", i:"2609.19252", n:"Cosmological Correlators from Scattering Amplitudes: A Review"},
  {t:"qft", i:"2609.17861", n:"Six Particles, Infinite Optimism: Towards Positivity Bounds for Six-Point Amplitudes"},
  // Beyond the Standard Model
  {t:"bsm", i:"2609.16728", n:"Searching for new physics with contact-free transitions in muonic atoms"},
  {t:"bsm", i:"2609.16342", n:"Top-quark pair production sensitivity to heavy new physics at the FCC-ee"},
  {t:"bsm", i:"2609.10382", n:"Searching for New Physics with Reinforcement Learning"},
  {t:"bsm", i:"2608.10104", n:"Precision Tests of SM and new physics with the COHERENT Ge-mini and TEXONO data"},
  {t:"bsm", i:"2607.22163", n:"Resolving Lorentz-Violating New Physics at ESSnuSB Using High-Statistics Complementarity with T2HK"},
  {t:"bsm", i:"2607.19323", n:"Towards anomaly detection searches for new physics signatures including Higgs bosons with weakly supervised machine learning"},
  // Dark Matter
  {t:"dm", i:"2609.26773", n:"Resonant neutrino flavor conversion within dark matter spikes"},
  {t:"dm", i:"2609.26698", n:"Model-Independent Sideband Constraints on Inelastic Dark Matter at the LZ High-Recoil Candidate"},
  {t:"dm", i:"2609.26611", n:"Dark-matter relay for ultra-high-energy cosmic rays"},
  {t:"dm", i:"2609.26570", n:"A Simple Dark Matter Model to Explain the LZ Event and Galactic Center Excess"},
  {t:"dm", i:"2609.26545", n:"Probing dark matter below the neutrino floor through NMSSM Higgs cascade decays at the HL-LHC"},
  {t:"dm", i:"2609.26533", n:"The compressed bino--wino dark matter in the GmSUGRA and the LHC soft-lepton searches"},
  // Axions & ALPs
  {t:"axion", i:"2609.24714", n:"The phenomenology of Axion Relic Pockets"},
  {t:"axion", i:"2609.24085", n:"Constraints on Axion-like Dark Matter from Cosmic Birefringence with a Polarization Array of Repeating Fast Radio Bursts"},
  {t:"axion", i:"2609.22698", n:"First-Principles Determination of the QCD Contribution to the Axion-Photon Coupling Using Domain-Wall Fermions"},
  {t:"axion", i:"2609.22570", n:"Probing light axion-like particles in vector boson fusion at CMS with data parking and scouting"},
  {t:"axion", i:"2609.21991", n:"Searching for Axions from Atmospheric Kaon Decays"},
  {t:"axion", i:"2609.20911", n:"Calculating Axion-Matter Couplings in String Theory"},
  // Dark Photons
  {t:"dp", i:"2609.24527", n:"Probing Massive Invisible Dark Photons in Higgs Decays via Gluon--Gluon Fusion at ATLAS Run 3"},
  {t:"dp", i:"2609.25114", n:"Elastic toroidal vector dark matter through a dark photon in the LUX-ZEPLIN high recoil window"},
  {t:"dp", i:"2609.23475", n:"Dark photon portal dark matter with low-temperature reheating"},
  {t:"dp", i:"2609.22739", n:"Kaluza--Klein Dark-Photon Mediation of Inelastic Dark Matter at LUX-ZEPLIN"},
  {t:"dp", i:"2609.22423", n:"Resonant Gravitational Production of Chiral Dark Photons"},
  {t:"dp", i:"2609.21648", n:"Dark photons in exotic Higgs boson decays at FCC-ee"},
  // Primordial Black Holes
  {t:"pbh", i:"2609.20329", n:"Predictions on the abundance of primordial black holes: results from the SMILE VLBI milli-lensing sample"},
  {t:"pbh", i:"2609.19270", n:"Lukewarm inflation, primordial black holes and gravitational waves"},
  {t:"pbh", i:"2609.12867", n:"Probing Inflationary Origins of Primordial Black Holes with LIGO--Virgo--KAGRA O1--O4a data"},
  {t:"pbh", i:"2609.12476", n:"A semicoherent resampling method for long-transient gravitational wave searches with applications to subsolar-mass primordial black-hole binaries"},
  {t:"pbh", i:"2609.12044", n:"Constraining dark matter using 20-year INTEGRAL/IBIS observations I: Primordial black holes"},
  {t:"pbh", i:"2609.11891", n:"Reconstructing Early Primordial Black Hole Domination from Gravitational-Wave Backgrounds"},
  // Gravitational Waves
  {t:"gw", i:"2609.25522", n:"Quadratic Gravitational-Wave Scattering by Kerr Black Holes"},
  {t:"gw", i:"2609.25225", n:"Gravitational wave signatures of subsolar neutron star formation in collapsar disks"},
  {t:"gw", i:"2609.25003", n:"Analytical estimates of core optics stray light noise and design requirements for ground based gravitational wave detectors"},
  {t:"gw", i:"2609.24428", n:"Do gravitational waves assist the genuine tripartite entanglement harvesting?"},
  {t:"gw", i:"2609.23865", n:"Signatures in the local interstellar medium of electromagnetic radiation produced by neutron star gravitational waves"},
  {t:"gw", i:"2609.22660", n:"Stereoscopic gravitational-wave probe: Gravitational lensing of a binary merger in active galactic nuclei"},
  // Neutrino Physics
  {t:"nu", i:"2609.25239", n:"Before WIMPs: Neutrinos and the origins of particle dark matter"},
  {t:"nu", i:"2609.25229", n:"Fast Surrogate for the Earth Matter Effect on Solar Neutrinos"},
  {t:"nu", i:"2609.24887", n:"A New Probe of Strongly-Interacting Dark Sector using Neutrino Telescopes"},
  {t:"nu", i:"2609.22806", n:"Gamma-Ray Echo as a Probe of Supernova Neutrino Emission Anisotropy and Long-Baseline Effects"},
  {t:"nu", i:"2609.21768", n:"AGN and DSNB Neutrino Oscillation in Dark Matter Background"},
  {t:"nu", i:"2609.21408", n:"Anomalous Matter Potentials in Earth's Inner Core: A Phenomenological Probe of Dark Matter and Light Sterile Neutrinos"},
  // Collider Physics
  {t:"coll", i:"2609.25601", n:"Electroweak phase transition triggered by a long-lived scalar and LHC searches"},
  {t:"coll", i:"2609.23708", n:"Probing Matter Unification through Higgs Physics at the LHC"},
  {t:"coll", i:"2609.23576", n:"Toponium Production at Future Muon Colliders and in heavy ion ultraperipheral collisions"},
  {t:"coll", i:"2609.22484", n:"Machine Learning for Invisible Dark Boson Searches at the Electron-Ion Collider"},
  {t:"coll", i:"2609.21011", n:"Endothermic Z'-Portal Dark Matter: LZ-LHC Complementarity"},
  {t:"coll", i:"2609.19919", n:"New massive resonances at the LHC"},
  // Higgs Physics
  {t:"higgs", i:"2609.26413", n:"The Super-Composite Higgs"},
  {t:"higgs", i:"2609.25217", n:"Limitations of quantum tomography in Higgs-boson decays to four leptons"},
  {t:"higgs", i:"2609.23829", n:"Baryogenesis and dark matter freeze-in from Higgs interactions"},
  {t:"higgs", i:"2609.19918", n:"Colour sextet baryons in composite Higgs models"},
  {t:"higgs", i:"2609.19258", n:"A phenomenological profile of Higgs portals at future colliders"},
  {t:"higgs", i:"2609.18168", n:"Constraints of Big Bang Nucleosynthesis and Cosmological Observations on varying Higgs VEV"},
  // Supersymmetry
  {t:"susy", i:"2609.15742", n:"Explain the LZ High-Energy Recoil Event with Inelastic Sneutrino Dark Matter in Supersymmetry"},
  {t:"susy", i:"2609.12914", n:"What has the LHC told us about the electroweakino sector of the Minimal Supersymmetric Standard Model?"},
  {t:"susy", i:"2609.11241", n:"Higgsino dark matter in the Starobinsky supergravity with the MSSM in light of the LUX-ZEPLIN event"},
  {t:"susy", i:"2609.04333", n:"Reinterpreting Supersymmetry"},
  {t:"susy", i:"2608.23555", n:"Two-loop renormalisation and Higgs phenomenology in the five-dimensional MSSM"},
  {t:"susy", i:"2608.11869", n:"Higgs Mass and CP violating Phases Implications on the SUSY Breaking Scale in MSSM"},
  // String Theory
  {t:"string", i:"2609.25203", n:"The landscape and the swampland of O(3,3) gauged supergravities"},
  {t:"string", i:"2609.24939", n:"Chiral Carroll string near Schwarzschild black hole"},
  {t:"string", i:"2609.24366", n:"T-duality of string charge density/bit threads correspondence in type II supergravity"},
  {t:"string", i:"2609.20919", n:"Massive type 0A string theory and M-theory"},
  {t:"string", i:"2609.17660", n:"Bosonic String Amplitudes From Ribbon Graphs"},
  {t:"string", i:"2609.15929", n:"String charge density/bit threads correspondence and its S-duality in type IIB supergravity"},
  // Extra Dimensions
  {t:"xdim", i:"2609.25207", n:"A Quantum-Mechanical Model for the M5-Brane"},
  {t:"xdim", i:"2609.23079", n:"Toroidal Charged AdS Branes and Deformed Toda Equations"},
  {t:"xdim", i:"2609.21421", n:"Complex scalar field thick branes: stability of linear perturbation and evolution of scalar Kaluza-Klein modes coupled with gravity"},
  {t:"xdim", i:"2609.20806", n:"M2-brane matrix models and Fermi gas on affine ABCD quivers"},
  {t:"xdim", i:"2609.17858", n:"Matter Swapping between Two Branes: A Local Type IIB D3-D7-D3 Realization of Charged-Fermion Mixing via E3 Instantons"},
  {t:"xdim", i:"2609.17528", n:"Exact Black Branes in General Dimensions in Higher-Curvature Scalar-Tensor Gravity"},
  // Inflation
  {t:"inf", i:"2609.26553", n:"Constraining Inflation with Little Red Dots"},
  {t:"inf", i:"2609.24992", n:"Multi-Stage and Multi-Field Inflation in Random Inflationary Landscapes"},
  {t:"inf", i:"2609.24912", n:"Gauss--Bonnet running and the de Sitter saddle of quadratic gravity inflation"},
  {t:"inf", i:"2609.23029", n:"Thermal-acoustic fermionic dynamics and primordial perturbations in warm Yukawa inflation"},
  {t:"inf", i:"2609.20801", n:"The axion mass in the post-inflationary scenario in a minimal scaling model"},
  {t:"inf", i:"2609.20622", n:"The return of Palatini inflationary attractors: Universal mapping of observables"},
  // Early Universe
  {t:"early", i:"2609.26767", n:"Tachyonic particle production in strongly supercooled phase transitions"},
  {t:"early", i:"2609.25950", n:"Big Bang Nucleosynthesis Confronts Domain Walls and First-Order Phase Transitions as the Pulsar Timing Array Explanations"},
  {t:"early", i:"2609.19271", n:"Probing Scalar-Induced First-Order Phase Transitions with the Diffuse Supernova Neutrino Background"},
  {t:"early", i:"2608.30985", n:"Resonant Dynamics of Gravitational Wave and Chiral Alfvén wave in the Early Universe"},
  {t:"early", i:"2608.30115", n:"Building a Better Beta: Nucleation and Timescales in Cosmological Phase Transitions"},
  {t:"early", i:"2608.20897", n:"Probing cosmological phase transitions with SKAO through nano-Hz gravitational-wave portal"},
  // Baryogenesis & Leptogenesis
  {t:"baryo", i:"2609.24990", n:"Three-Flavoured Thermal Leptogenesis Without Tuning"},
  {t:"baryo", i:"2609.21745", n:"Leptogenesis and Planck-scale black hole remnants in a Pati-Salam cosmology"},
  {t:"baryo", i:"2609.20033", n:"On the Maximal CP Violation in Leptogenesis with Two Right Handed Neutrinos"},
  {t:"baryo", i:"2609.12542", n:"Leptogenesis Determined By Low Energy Parameters"},
  {t:"baryo", i:"2609.08462", n:"Vacuum Decay and Baryogenesis Associated with Primordial Black Holes at Finite Temperature"},
  {t:"baryo", i:"2609.07130", n:"Majoron-driven spontaneous leptogenesis in type-II seesaw model"},
  // Astroparticle Physics
  {t:"astro", i:"2609.26436", n:"Neutrino Astronomy at High Energies - An Experimental Review"},
  {t:"astro", i:"2609.22577", n:"Resolving the Galactic Center Region's Gamma-Ray Emission and Searching for its Neutrino Counterpart with HAWC and IceCube"},
  {t:"astro", i:"2609.21278", n:"Neutrino Emission from Proton Photon Jet Interactions in Microquasars"},
  {t:"astro", i:"2609.19477", n:"Lepto-hadronic modeling of blazars associated with well-reconstructed high-energy neutrino events"},
  {t:"astro", i:"2609.19256", n:"Collective flavor conversion in dense neutrino plasmas"},
  {t:"astro", i:"2609.18233", n:"Toward Autonomous Radio Follow-up of Multi-messenger Transients with RADAR: From Alert Parsing to Inference and Observation Scheduling"},
  // Cosmic Rays
  {t:"cr", i:"2609.24982", n:"A closer look at the LZ 248 keV event through the lens of cosmic-ray boosted dark matter"},
  {t:"cr", i:"2609.23480", n:"The role of photon fields of local sources in the formation of the cosmic rays energy spectrum"},
  {t:"cr", i:"2609.22480", n:"Importance of the Resonant Cosmic-Ray Streaming Instability Upstream of Collisionless Shocks"},
  {t:"cr", i:"2609.18383", n:"On the importance of cosmic-ray background in the Atomki anomaly"},
  {t:"cr", i:"2609.18226", n:"Detectability of 100 TeV Gamma Rays from PeV Cosmic Rays Accelerated in the Early Phase of a Supernova Shock Wave"},
  {t:"cr", i:"2609.15719", n:"Iron Nuclei with Energy of 10^19 eV in Extragalactic Cosmic Rays Near Earth"},
  // Gamma-Ray Astronomy
  {t:"gamma", i:"2609.22426", n:"GRB 220706A: a gamma-ray burst with a month-long engine and a luminous supernova"},
  {t:"gamma", i:"2609.21411", n:"Gamma-ray Quasi-periodic Oscillations in the Changing Look Blazar B2 1420+326 (OQ 334)"},
  {t:"gamma", i:"2609.21343", n:"A Gamma-ray Emitting Head-Tail Radio Galaxy Swimming Through the Hot Medium of the Merging Cluster Abell 3627"},
  {t:"gamma", i:"2609.20944", n:"Systematic Uncertainties and Their Impact on Gamma-Ray Searches for Dark Matter in Dwarf Galaxies"},
  {t:"gamma", i:"2609.19259", n:"On the Clustering Bias of Unresolved Gamma-Ray Sources"},
  {t:"gamma", i:"2609.17776", n:"The Hidden Evolution of Gamma-Ray Burst Jets Revealed by Gravitational Waves"},
  // Black Hole Physics
  {t:"bh", i:"2609.26724", n:"Quasinormal modes and quantum black hole interiors"},
  {t:"bh", i:"2609.25667", n:"Lensing Signatures of a Primary Hair Black Hole Solution"},
  {t:"bh", i:"2609.25565", n:"Axial Perturbations of Charged Kiselev Black Holes in Rastall Gravity: Matter Response and Quasinormal Modes"},
  {t:"bh", i:"2609.25530", n:"Holographic description of RN-like black hole in bumblebee gravity"},
  {t:"bh", i:"2609.25281", n:"Black Hole Perturbation Toolkit: Low frequency and post-Newtonian expansions"},
  {t:"bh", i:"2609.25228", n:"Accurate Black Hole Quasinormal Modes, Regge Poles, and Greybody Factors from Light Ring Ladder Symmetry"},
  // Modified Gravity
  {t:"modgrav", i:"2609.25910", n:"Gravitational Imprints of Dark Energy in Neutron Stars"},
  {t:"modgrav", i:"2609.24926", n:"Observational Features of Nonsingular Rotating Black Holes in the Dark-Energy Dominated Universe"},
  {t:"modgrav", i:"2609.24361", n:"A novel phenomenological parametrization of dynamical dark energy via matter-gravity coupling"},
  {t:"modgrav", i:"2609.24351", n:"Probing modified gravity with galaxy-cluster-lensed gravitational-wave time delays: impact of systematic effects"},
  {t:"modgrav", i:"2609.23704", n:"Bi-scalar-tensor theory: a spatially covariant gravity approach"},
  {t:"modgrav", i:"2609.25090", n:"Comparing Mass-Varying Neutrino Dark Energy Models with DESI DR2: Cosmological Constraints and Bayesian Evidence"},
  // Quantum Gravity
  {t:"qg", i:"2609.26641", n:"Density-driven reversal of flavour-entanglement anisotropy in the D3-D7 holographic conductor"},
  {t:"qg", i:"2609.24557", n:"On the (In)equivalence of de Sitter and Holographic Entanglement Entropies in Lovelock Gravity"},
  {t:"qg", i:"2609.24227", n:"Critical Kasner scaling from Cauchy-horizon collapse near holographic phase transitions"},
  {t:"qg", i:"2609.22890", n:"Time and causality in quantum gravity"},
  {t:"qg", i:"2609.22504", n:"Tripartite Form Universality in Holographic Entropy Inequalities"},
  {t:"qg", i:"2609.21471", n:"A Geodesic Route toward Holography beyond AdS: Tessellating the Schwarzschild Black Hole"},
  // Effective Field Theory
  {t:"eft", i:"2609.20914", n:"All-Order Helicity Selection Rules in Effective Field Theories"},
  {t:"eft", i:"2609.20742", n:"Environmental Effects in Post-Minkowskian Dynamics: Effective Field Theory, Feynman Rules, and Ward Identities for Compact Objects in Relativistic Fluids"},
  {t:"eft", i:"2609.12051", n:"Muon decay across scales: from LEFT to SMEFT"},
  {t:"eft", i:"2609.11767", n:"Massless-Massive Amplitude Correspondence III: Massive Amplitude Bases in the SMEFT"},
  {t:"eft", i:"2609.11055", n:"A Tale of Two Gauges: Effective Field Theory for Relativistic Behavior of Cosmological Axions"},
  {t:"eft", i:"2609.06624", n:"Effective Field Theory of Protonium"},
  // Flavour Physics
  {t:"flav", i:"2609.14440", n:"Thermal modifications of the B-meson spectrum"},
  {t:"flav", i:"2609.08350", n:"Top-quark flavor-changing neutral currents and charged-lepton flavor violation in a generational three-Higgs-doublet model"},
  {t:"flav", i:"2608.28149", n:"Fixed points of the CKM matrix renormalization group running to all orders in perturbation theory"},
  {t:"flav", i:"2608.17491", n:"An Exact Analytical Bridge from Complex Yukawa Couplings to Fermion Masses and CKM/PMNS Mixing"},
  {t:"flav", i:"2608.05269", n:"Baryogenesis via the CKM Matrix with Minimal Flavor Violation"},
  {t:"flav", i:"2608.01445", n:"The CKM sector of the exceptional-Jordan programme: finite-Dirac mass moduli, two conditional angle estimates, and the weak-to-mass bridge"},
  // CMB Physics
  {t:"cmb", i:"2609.24998", n:"Statistical Fluctuations as Primordial Correlators in the CMB: Finite Chemical Potential Thermodynamics"},
  {t:"cmb", i:"2609.19296", n:"A Global Overview of Starobinsky Inflation beyond slow-roll with CMB-BAO data"},
  {t:"cmb", i:"2609.17829", n:"Optimising instrument concepts with Machine Learning: Application to CMB spectral distortion experiments"},
  {t:"cmb", i:"2609.16194", n:"Peering Beyond the Veil of Last Scattering: A View of the Universe with CMB Spectral Distortions"},
  {t:"cmb", i:"2609.17618", n:"FOSSIL: A future mission for CMB spectral distortion measurements"},
  {t:"cmb", i:"2609.16128", n:"CMB-HD Foregrounds: Simulations, Source Detection, and Foreground Removal"},
  // Large-Scale Structure
  {t:"lss", i:"2609.25389", n:"Cross-Bispectrum Constraints from HI Intensity Mapping and Galaxy Surveys"},
  {t:"lss", i:"2609.24948", n:"Two-dimensional weak lensing shear for cluster mass, concentration, ellipticity and miscentering estimation"},
  {t:"lss", i:"2609.22543", n:"The Deep Learning Halo Definer: A Multimodal Framework for Halo Mass and Gas Fraction Inference on Galaxy Groups and Clusters"},
  {t:"lss", i:"2609.20571", n:"Euclid: Galaxy cluster detection through the weak lensing effect - algorithm assessment and selection"},
  {t:"lss", i:"2609.19509", n:"The extreme Disturbed Galaxy Cluster Sample (eDGeS): Spectroscopy and Dynamical Analysis of the eROSITA-Selected Merging Galaxy Cluster Candidate 1eRASS J025859.4-193727"},
  {t:"lss", i:"2609.16425", n:"Right Energy, Wrong Profile: Why the 43 GeV Cluster Line Is Unlikely to Be Dark Matter"}
];

/* ---- foundational shelf --------------------------------------------- */
/* Canon, by author and year. Links resolve to a live arXiv search so no
   identifier is asserted that has not been verified.                    */
window.QC_CANON = [
  {t:"axion", a:"Peccei & Quinn", y:1977, n:"CP conservation in the presence of pseudoparticles"},
  {t:"axion", a:"Weinberg", y:1978, n:"A new light boson?"},
  {t:"axion", a:"Wilczek", y:1978, n:"Problem of strong P and T invariance in the presence of instantons"},
  {t:"axion", a:"Preskill, Wise & Wilczek", y:1983, n:"Cosmology of the invisible axion"},
  {t:"dp",    a:"Holdom", y:1986, n:"Two U(1)'s and epsilon charge shifts"},
  {t:"pbh",   a:"Zel'dovich & Novikov", y:1967, n:"The hypothesis of cores retarded during expansion"},
  {t:"pbh",   a:"Hawking", y:1974, n:"Black hole explosions?"},
  {t:"pbh",   a:"Carr & Hawking", y:1974, n:"Black holes in the early universe"},
  {t:"bh",    a:"Bekenstein", y:1973, n:"Black holes and entropy"},
  {t:"bh",    a:"Page", y:1976, n:"Particle emission rates from a black hole"},
  {t:"inf",   a:"Guth", y:1981, n:"Inflationary universe: a possible solution to the horizon and flatness problems"},
  {t:"inf",   a:"Starobinsky", y:1980, n:"A new type of isotropic cosmological models without singularity"},
  {t:"inf",   a:"Mukhanov & Chibisov", y:1981, n:"Quantum fluctuations and a nonsingular universe"},
  {t:"inf",   a:"Linde", y:1982, n:"A new inflationary universe scenario"},
  {t:"baryo", a:"Sakharov", y:1967, n:"Violation of CP invariance, C asymmetry, and baryon asymmetry of the universe"},
  {t:"baryo", a:"Fukugita & Yanagida", y:1986, n:"Baryogenesis without grand unification"},
  {t:"baryo", a:"Kuzmin, Rubakov & Shaposhnikov", y:1985, n:"On anomalous electroweak baryon-number non-conservation"},
  {t:"nu",    a:"Pontecorvo", y:1957, n:"Mesonium and antimesonium"},
  {t:"nu",    a:"Maki, Nakagawa & Sakata", y:1962, n:"Remarks on the unified model of elementary particles"},
  {t:"nu",    a:"Minkowski", y:1977, n:"mu to e gamma at a rate of one out of a billion muon decays?"},
  {t:"nu",    a:"Wolfenstein", y:1978, n:"Neutrino oscillations in matter"},
  {t:"higgs", a:"Englert & Brout", y:1964, n:"Broken symmetry and the mass of gauge vector mesons"},
  {t:"higgs", a:"Higgs", y:1964, n:"Broken symmetries and the masses of gauge bosons"},
  {t:"pheno", a:"Weinberg", y:1967, n:"A model of leptons"},
  {t:"qft",   a:"'t Hooft & Veltman", y:1972, n:"Regularization and renormalization of gauge fields"},
  {t:"qft",   a:"Wilson", y:1971, n:"Renormalization group and critical phenomena"},
  {t:"susy",  a:"Wess & Zumino", y:1974, n:"Supergauge transformations in four dimensions"},
  {t:"susy",  a:"Dimopoulos & Georgi", y:1981, n:"Softly broken supersymmetry and SU(5)"},
  {t:"string",a:"Maldacena", y:1997, n:"The large N limit of superconformal field theories and supergravity"},
  {t:"xdim",  a:"Arkani-Hamed, Dimopoulos & Dvali", y:1998, n:"The hierarchy problem and new dimensions at a millimeter"},
  {t:"xdim",  a:"Randall & Sundrum", y:1999, n:"A large mass hierarchy from a small extra dimension"},
  {t:"gw",    a:"LIGO & Virgo Collaborations", y:2016, n:"Observation of gravitational waves from a binary black hole merger"},
  {t:"gw",    a:"Hellings & Downs", y:1983, n:"Upper limits on the isotropic gravitational radiation background from pulsar timing analysis"},
  {t:"cmb",   a:"Sachs & Wolfe", y:1967, n:"Perturbations of a cosmological model and angular variations of the microwave background"},
  {t:"lss",   a:"Press & Schechter", y:1974, n:"Formation of galaxies and clusters of galaxies by self-similar gravitational condensation"},
  {t:"dm",    a:"Rubin & Ford", y:1970, n:"Rotation of the Andromeda nebula from a spectroscopic survey of emission regions"},
  {t:"dm",    a:"Zwicky", y:1933, n:"Die Rotverschiebung von extragalaktischen Nebeln"},
  {t:"eft",   a:"Buchmuller & Wyler", y:1986, n:"Effective Lagrangian analysis of new interactions and flavour conservation"},
  {t:"flav",  a:"Cabibbo", y:1963, n:"Unitary symmetry and leptonic decays"},
  {t:"flav",  a:"Kobayashi & Maskawa", y:1973, n:"CP violation in the renormalizable theory of weak interaction"},
  {t:"modgrav",a:"Brans & Dicke", y:1961, n:"Mach's principle and a relativistic theory of gravitation"},
  {t:"qg",    a:"Unruh", y:1976, n:"Notes on black-hole evaporation"},
  {t:"cr",    a:"Greisen; Zatsepin & Kuzmin", y:1966, n:"End to the cosmic-ray spectrum? (the GZK cutoff)"},
  {t:"bsm",   a:"Georgi & Glashow", y:1974, n:"Unity of all elementary-particle forces"},
  {t:"coll",  a:"Drell & Yan", y:1970, n:"Massive lepton-pair production in hadron-hadron collisions"},
  {t:"astro", a:"Greisen", y:1960, n:"Cosmic ray showers"},
  {t:"gamma", a:"Gould & Schreder", y:1967, n:"Opacity of the universe to high-energy photons"},
  {t:"early", a:"Witten", y:1984, n:"Cosmic separation of phases"}
];
